<?php

namespace OroAcademy\Bundle\IssueBundle\Entity;

/**
 * IssueResolutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueResolutionRepository extends \Doctrine\ORM\EntityRepository
{
}
