datagrid:
    # The Dashboard Grid with my active issues
    dashboard-my-issues-grid:
        options:
            entityHint: call
            toolbarOptions:
                addColumnManager: false
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10
        source:
            acl_resource: view_issue
            type: orm
            query:
                select:
                    - i.id
                    - i.summary
                    - i.code
                    - t.label as type
                    - p.label as priority
                    - wfs.label as status
                    - i.createdAt
                from:
                    - { table: OroAcademyIssueBundle:Issue, alias: i }
                join:
                    left:
                        - { join: i.type, alias: t, conditionType: WITH }
                        - { join: i.priority, alias: p, conditionType: WITH }
                        - { join: i.workflowStep, alias: wfs }
                where:
                    and:
                        - :user_id MEMBER OF i.collaborators
            bind_parameters:
                user_id: userId

        columns:
            code:
                label: Code
            summary:
                label: Summary
            type:
                label: Type
            priority:
                label: Priority
            status:
                label: Status
            createdAt:
                label: Created
                frontend_type: date
        properties:
            id: ~
            view_link:
                type: url
                route: oroacademy_view_issue
                params:
                    - id
        sorters:
            columns:
                createdAt:
                    data_name: i.createdAt
            default:
                createdAt:
                  DESC
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          eye-open
                acl_resource:  view_issue
                rowAction:     true

    # Main Issue grid
    issue-grid:
        source:
            acl_resource: view_issue
            type: orm
            query:
                select:
                    - i.id
                    - i.summary
                    - i.code
                    - i.description
                    - t.label as type
                    - p.label as priority
                    - p.value as priorityOrder
                    - r.label as resolution
                    - wfs.label as status
                    - wfs.stepOrder as statusOrder
                    - CONCAT(rep.firstName, CONCAT(' ', rep.lastName)) as reporter
                    - CONCAT(asgn.firstName, CONCAT(' ', asgn.lastName)) as assignee
                    - i.createdAt
                    - i.updatedAt
                    - u.id as collaborators
                from:
                    - { table: OroAcademyIssueBundle:Issue, alias: i }
                join:
                    left:
                        - { join: i.type, alias: t, conditionType: WITH }
                        - { join: i.resolution, alias: r, conditionType: WITH }
                        - { join: i.priority, alias: p, conditionType: WITH }
                        - { join: i.reporter, alias: rep, conditionType: WITH }
                        - { join: i.assignee, alias: asgn, conditionType: WITH }
                        - { join: i.collaborators, alias: u, conditionType: WITH }
                        - { join: i.workflowStep, alias: wfs }
                groupBy: i.id

        columns:
            code:
                label: Code
            summary:
                label: Summary
            type:
                label: Type
            priority:
                label: Priority
            status:
                label: Status
            resolution:
                label: Resolution
            reporter:
                label: Reporter
            assignee:
                label: Assignee
            createdAt:
                label: Created
                frontend_type: date
            updatedAt:
                label: Updated
                frontend_type: date
        properties:
            id: ~
            update_link:
                type: url
                route: oroacademy_update_issue
                params:
                    - id
            view_link:
                type: url
                route: oroacademy_view_issue
                params:
                    - id
            delete_link:
                type: url
                route: oroacademy_api_delete_issue
                params:
                    - id
        sorters:
            columns:
                type:
                    data_name: type
                summary:
                    data_name: i.summary
                code:
                    data_name: i.code
                resolution:
                    data_name: resolution
                priority:
                    data_name: priorityOrder
                status:
                    data_name: statusOrder
                updatedAt:
                    data_name: i.updatedAt
                createdAt:
                    data_name: i.createdAt
                reporter:
                    data_name: reporter
                assignee:
                    data_name: assignee
            default:
                model: DESC
        filters:
            columns:
                code:
                    type: string
                    data_name: i.code
                createdAt:
                    type: date
                    data_name: i.createdAt
                collaborated:
                    type: entity
                    label: Collaborator
                    data_name: collaborators
                    options:
                        field_options:
                            class: OroUserBundle:User
                            multiple: false
                            property: fullName
                            translatable_options: false
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          eye-open
                acl_resource:  view_issue
                rowAction:     true
            update:
                type:          navigate
                label:         Update
                link:          update_link
                icon:          edit
                acl_resource:  update_issue
            delete:
                type:          delete
                label:         Delete
                link:          delete_link
                icon:          trash
                acl_resource:  api_delete_issue

    # Main issue grid without the pagination and default sorting order
    my-issue-grid:
       extends: issue-grid
       source:
           query:
               where:
                   and:
                       - (u.id = :id)
           bind_parameters:
               - id
       filters: ~
       sorters:
           columns:
               createdAt:
                  data_name: i.createdAt
           default:
               createdAt:
                  DESC