oro_menu_config:
    items:
        issues:
            label: oroacademy.issue.entity_plural_label
            uri: '#'

        issue_shortcut:
            label: oroacademy.issue.navigation.menu_list.label
            route: oroacademy_issue_index
    tree:
        application_menu:
            children:
                issues:
                    children:
                        issue_shortcut: ~

oro_titles:
    oroacademy_issue_index: oroacademy.titles.issues
    oroacademy_my_issue_grid: oroacademy.titles.my_issues
    oroacademy_view_issue: '%%entity%%'
    oroacademy_create_issue: oroacademy.titles.create_issue
    oroacademy_create_subtask_issue: oroacademy.titles.create_subtask
    oroacademy_update_issue: oroacademy.titles.update_issue
