oro_menu_config:
    items:
        issues:
            label: oroacademy.issue.entity_plural_label
            uri: '#'

        oroacademy_issue_index:
            label: oroacademy.issue.navigation.menu_list
            route: 'oroacademy_issue_index'
            extras:
              routes: [ 'oroacademy_view_issue', 'oroacademy_update_issue', 'oroacademy_create_issue', 'oroacademy_create_subtask_issue' ]

        oroacademy_my_issue_grid:
            label: oroacademy.issue.navigation.menu_my_issues
            route: 'oroacademy_my_issue_grid'

    tree:
        application_menu:
            children:
                issues:
                    children:
                        oroacademy_issue_index: ~
                        oroacademy_my_issue_grid: ~

oro_titles:
    oroacademy_issue_index: oroacademy.titles.issues
    oroacademy_my_issue_grid: oroacademy.titles.my_issues
    oroacademy_view_issue: '%%entity%%'
    oroacademy_create_issue: oroacademy.titles.create_issue
    oroacademy_create_subtask_issue: oroacademy.titles.create_subtask
    oroacademy_update_issue: oroacademy.titles.update_issue
