oro_menu_config:
    items:
        issues:
            label: oroacademy.issue.entity_plural_label
            uri: '#'

        issue_shortcut:
            label: oroacademy.issue.navigation.menu_list.label
            route: oroacademy_issue_index
    tree:
        application_menu:
            children:
                issues:
                    children:
                        issue_shortcut: ~
