oro_menu_config:
    items:
        issues:
            label: Issues
            uri: '#'

        issue_shortcut:
            label: List of Issues
            route: oroacademy_issue_index
    tree:
        application_menu:
            children:
                issues:
                    children:
                        issue_shortcut: ~