placeholders:
    view_content_data_additional_information:
        items:
            oroacademy_user_view_issue_grid: ~

items:
    oroacademy_user_view_issue_grid:
        template: OroAcademyIssueBundle:User:issueGrid.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)

    oroacademy_create_issue_button:
        template: OroAcademyIssueBundle:User:createIssueButton.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)
        acl: create_issue

    oroacademy_create_issue_link:
        template: OroAcademyIssueBundle:User:createIssueLink.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)
        acl: create_issue
