placeholders:
    view_content_data_additional_information:
        items:
            oroacademy_user_view_issue_grid: ~
    view_navButtons_after:
        items:
            oroacademy_create_issue_button: ~

items:
    oroacademy_user_view_issue_grid:
        template: OroAcademyIssueBundle:User:issueGrid.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)

    oroacademy_create_issue_button:
        template: OroAcademyIssueBundle:User:createIssueButton.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)
        acl: create_issue

    oroacademy_send_email_button:
        template: OroAcademyBundle:Email:activityButton.html.twig
        acl: oro_email_email_create

    oroacademy_send_email_link:
        template: OroAcademyBundle:Email:activityLink.html.twig
        acl: oro_email_email_create
