services:
  oroacademy_issue_manager.api:
      class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
      parent: oro_soap.manager.entity_manager.abstract
      arguments:
        - OroAcademy/Bundle/IssueBundle/Entity/Issue
        - "@doctrine.orm.entity_manager"

  oroacademy_issue_form_helper.api:
      class: OroAcademy\Bundle\IssueBundle\Form\Handler\FormEntityRelationHelper
      arguments: ["@doctrine.orm.entity_manager"]

  oroacademy_issue_handler.api:
      class: OroAcademy\Bundle\IssueBundle\Form\Handler\IssueHandler
      scope: request
      arguments:
        - '@oroacademy_issue_form_helper.api'
        - '@request'
        - '@doctrine.orm.entity_manager'
        - '@oroacademy_issue_form_builder'

  oroacademy_issue_listener:
      class: OroAcademy\Bundle\IssueBundle\EventListener\IssueNoteUpdatesListener
      tags:
        - { name: doctrine.event_listener, event: postPersist, connection: default }
        - { name: doctrine.event_listener, event: postUpdate, connection: default }
        - { name: doctrine.event_listener, event: postRemove, connection: default }

  oroacademy_workflow.action.add_collaborator:
      class: OroAcademy\Bundle\IssueBundle\Workflow\Action\AddCollaboratorAction
      arguments:
        - '@oro_workflow.context_accessor'
        - '@doctrine'
      tags:
        - { name: oro_workflow.action, alias: add_collaborator }

  oroacademy_form_helper.subtask:
      class: OroAcademy\Bundle\IssueBundle\Helper\SubtaskFormHelper

  oroacademy_issue_form_builder:
      class: OroAcademy\Bundle\IssueBundle\Helper\IssueFormBuilder
      arguments:
        - '@oroacademy_form_helper.subtask'
        - '@form.factory'
        - '@request_stack'