services:
  oroacademy_issue_manager.api:
      class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
      parent: oro_soap.manager.entity_manager.abstract
      arguments:
        - OroAcademy/Bundle/IssueBundle/Entity/Issue
        - "@doctrine.orm.entity_manager"

  oroacademy_issue_form_helper.api:
      class: OroAcademy\Bundle\IssueBundle\Form\Handler\FormEntityRelationHelper
      arguments: ["@doctrine.orm.entity_manager"]

  oroacademy_issue_form.api:
      class: Symfony\Component\Form\Form
      factory_method: createNamed
      factory_service: form.factory
      arguments: ["issue", "issue", null, {csrf_protection: false, allow_extra_fields: true, validation_groups: false}]

  oroacademy_issue_handler.api:
      class: OroAcademy\Bundle\IssueBundle\Form\Handler\IssueHandler
      scope: request
      arguments:
        - '@oroacademy_issue_form_helper.api'
        - '@request'
        - '@doctrine.orm.entity_manager'
      calls:
        - [ setForm, ['@oroacademy_issue_form.api' ]]

  oroacademy_issue_listener:
      class: OroAcademy\Bundle\IssueBundle\EventListener\IssueNoteUpdatesListener
      tags:
        - { name: doctrine.event_listener, event: postPersist, connection: default }
        - { name: doctrine.event_listener, event: postUpdate, connection: default }
        - { name: doctrine.event_listener, event: postRemove, connection: default }

  oroacademy_workflow.action.add_collaborator:
      class: OroAcademy\Bundle\IssueBundle\Workflow\Action\AddCollaboratorAction
      arguments:
        - '@oro_workflow.context_accessor'
        - '@doctrine'
      tags:
        - { name: oro_workflow.action, alias: add_collaborator }